# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          usedocker: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "buki-vs-balloons"
          heroku_email: "tiago.cambara21@gmail.com"