# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x  
      - name: Build the typscript
        run: | 
          npm i
          npm run build
      - name: check folder
        run: cd dist & ls
      - uses: akhileshns/heroku-deploy@v3.12.12
      - name: Build Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "buki-vs-balloons"
          heroku_email: "tiago.cambara21@gmail.com"